-- Template global de auditoria baseado em RDC 216/2004.
-- ~50 itens em 9 categorias, com pesos 1-3.
insert into public.audit_templates (id, company_id, name, items)
values (
  '00000000-0000-0000-0000-000000000216',
  null,
  'Roteiro RDC 216/2004 (boas praticas)',
  '[
    {"id":"e1","category":"Edificacao","text":"Pisos, paredes e tetos em bom estado, sem trincas, infiltracoes ou bolores","weight":2,"legal_ref":"RDC 216 4.1.1"},
    {"id":"e2","category":"Edificacao","text":"Portas e janelas com vedacao adequada e telas milimetricas","weight":2,"legal_ref":"RDC 216 4.1.4"},
    {"id":"e3","category":"Edificacao","text":"Iluminacao adequada e luminarias protegidas contra estilhacos","weight":1,"legal_ref":"RDC 216 4.1.10"},
    {"id":"e4","category":"Edificacao","text":"Ventilacao garante conforto termico e renovacao do ar","weight":2,"legal_ref":"RDC 216 4.1.11"},
    {"id":"e5","category":"Edificacao","text":"Lavatorios exclusivos para higiene das maos providos de sabonete, antisseptico e toalha descartavel","weight":3,"legal_ref":"RDC 216 4.1.13"},
    {"id":"eq1","category":"Equipamentos","text":"Equipamentos em bom estado de conservacao e funcionamento","weight":2,"legal_ref":"RDC 216 4.2.1"},
    {"id":"eq2","category":"Equipamentos","text":"Superficies de contato com alimentos lisas, integras, atoxicas e impermeaveis","weight":3,"legal_ref":"RDC 216 4.2.2"},
    {"id":"eq3","category":"Equipamentos","text":"Termometros calibrados e em uso (refrigerador, freezer, estufa)","weight":3,"legal_ref":"RDC 216 4.2.5"},
    {"id":"eq4","category":"Equipamentos","text":"Plano de manutencao preventiva documentado","weight":2,"legal_ref":"RDC 216 4.2.3"},
    {"id":"m1","category":"Manipuladores","text":"Uniformes limpos, completos e exclusivos da area de producao","weight":2,"legal_ref":"RDC 216 4.6.4"},
    {"id":"m2","category":"Manipuladores","text":"Maos lavadas corretamente nos momentos previstos","weight":3,"legal_ref":"RDC 216 4.6.6"},
    {"id":"m3","category":"Manipuladores","text":"Cabelos presos com touca; barba feita; sem adornos","weight":2,"legal_ref":"RDC 216 4.6.3"},
    {"id":"m4","category":"Manipuladores","text":"Manipuladores sem feridas ou doencas que comprometam a seguranca","weight":3,"legal_ref":"RDC 216 4.6.7"},
    {"id":"m5","category":"Manipuladores","text":"Capacitacao em boas praticas comprovada (registros)","weight":2,"legal_ref":"RDC 216 4.6.9"},
    {"id":"m6","category":"Manipuladores","text":"ASO (Atestado de Saude Ocupacional) atualizado","weight":3,"legal_ref":"RDC 216 4.6.7"},
    {"id":"mp1","category":"Materias-primas","text":"Recebimento conferindo temperatura, validade e integridade","weight":3,"legal_ref":"RDC 216 4.7.1"},
    {"id":"mp2","category":"Materias-primas","text":"Insumos armazenados em estrados, distantes do piso e paredes","weight":2,"legal_ref":"RDC 216 4.7.4"},
    {"id":"mp3","category":"Materias-primas","text":"Rotulagem com identificacao, data de recebimento e validade","weight":2,"legal_ref":"RDC 216 4.7.3"},
    {"id":"mp4","category":"Materias-primas","text":"Sistema PEPS/FIFO em uso","weight":2,"legal_ref":"RDC 216 4.7.5"},
    {"id":"h1","category":"Higienizacao","text":"Cronograma de higienizacao de instalacoes documentado e executado","weight":3,"legal_ref":"RDC 216 4.3.1"},
    {"id":"h2","category":"Higienizacao","text":"Produtos saneantes regularizados na ANVISA","weight":2,"legal_ref":"RDC 216 4.3.6"},
    {"id":"h3","category":"Higienizacao","text":"Diluicao e tempo de contato dos saneantes corretos","weight":3,"legal_ref":"RDC 216 4.3.5"},
    {"id":"h4","category":"Higienizacao","text":"Utensilios de limpeza identificados por area e armazenados separadamente","weight":1,"legal_ref":"RDC 216 4.3.8"},
    {"id":"p1","category":"Pragas","text":"Controle integrado de pragas com empresa licenciada","weight":3,"legal_ref":"RDC 216 4.4.1"},
    {"id":"p2","category":"Pragas","text":"Comprovantes e mapa de iscas disponiveis","weight":2,"legal_ref":"RDC 216 4.4.2"},
    {"id":"p3","category":"Pragas","text":"Ausencia de evidencias de pragas (fezes, ninhos, insetos)","weight":3,"legal_ref":"RDC 216 4.4.1"},
    {"id":"a1","category":"Agua","text":"Caixa d agua higienizada nos ultimos 6 meses","weight":3,"legal_ref":"RDC 216 4.5.2"},
    {"id":"a2","category":"Agua","text":"Laudo de potabilidade anual disponivel","weight":3,"legal_ref":"RDC 216 4.5.1"},
    {"id":"a3","category":"Agua","text":"Verificacao do cloro residual livre realizada e registrada","weight":2,"legal_ref":"RDC 216 4.5.1"},
    {"id":"r1","category":"Residuos","text":"Lixeiras com tampa, pedal e sacos plasticos em todas as areas","weight":2,"legal_ref":"RDC 216 4.8.1"},
    {"id":"r2","category":"Residuos","text":"Coleta interna frequente; area externa fechada e separada das areas de preparo","weight":2,"legal_ref":"RDC 216 4.8.2"},
    {"id":"r3","category":"Residuos","text":"Oleo usado armazenado separadamente e coletor licenciado","weight":1,"legal_ref":"RDC 216 4.8.3"},
    {"id":"prep1","category":"Preparacao","text":"Descongelamento sob refrigeracao (<= 4 C) ou microondas","weight":3,"legal_ref":"RDC 216 4.9.4"},
    {"id":"prep2","category":"Preparacao","text":"Coccao com temperatura interna >= 70 C verificada","weight":3,"legal_ref":"RDC 216 4.9.6"},
    {"id":"prep3","category":"Preparacao","text":"Resfriamento de 60 a 10 C em ate 2 horas","weight":3,"legal_ref":"RDC 216 4.9.10"},
    {"id":"prep4","category":"Preparacao","text":"Higienizacao de hortifrutis com solucao clorada 200 ppm por 15 min","weight":3,"legal_ref":"RDC 216 4.9.5"},
    {"id":"prep5","category":"Preparacao","text":"Etiquetas de validade em todos os produtos manipulados","weight":3,"legal_ref":"RDC 216 4.11.3"},
    {"id":"dist1","category":"Distribuicao","text":"Alimentos quentes mantidos acima de 60 C ou abaixo de 5 C","weight":3,"legal_ref":"RDC 216 4.11.4"},
    {"id":"dist2","category":"Distribuicao","text":"Tempo de exposicao em buffet controlado e registrado","weight":2,"legal_ref":"RDC 216 4.11.6"},
    {"id":"dist3","category":"Distribuicao","text":"Utensilios de servico separados por tipo de alimento","weight":1,"legal_ref":"RDC 216 4.11.5"},
    {"id":"doc1","category":"Documentacao","text":"Manual de Boas Praticas atualizado e acessivel","weight":3,"legal_ref":"RDC 216 4.11.1"},
    {"id":"doc2","category":"Documentacao","text":"POPs (higienizacao, agua, manipuladores, residuos, manutencao) implementados","weight":3,"legal_ref":"RDC 275/2002"},
    {"id":"doc3","category":"Documentacao","text":"Registros de temperatura mantidos por pelo menos 30 dias","weight":2,"legal_ref":"RDC 216 4.11.2"},
    {"id":"doc4","category":"Documentacao","text":"Alvara sanitario atualizado e visivel","weight":3,"legal_ref":""},
    {"id":"doc5","category":"Documentacao","text":"Responsavel tecnico (nutricionista) com registro no CRN ativo","weight":3,"legal_ref":""}
  ]'::jsonb
);